services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_service
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
networks:
  db:
    driver: bridge
volumes:
  postgres_data:
