services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_service
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
networks:
  db:
    driver: bridge
volumes:
  postgres_data:
