 insert into "users" (full_name, username, email, password, role) values
 ('Admin', 'admin', 'admin@domain.com', '$2a$10$AZkvnPuk4lJKg9vt/2cnB.T143dqy4bInOUpxLXNFCxi2GntZZDWC', 'ROLE_SUPER_ADMIN'),
 ('Editor', 'editor', 'editor@domain.com', '$2a$10$AZkvnPuk4lJKg9vt/2cnB.T143dqy4bInOUpxLXNFCxi2GntZZDWC', 'ROLE_EDITOR'),
 ('Contributor', 'contributor', 'contributor@domain.com', '$2a$10$AZkvnPuk4lJKg9vt/2cnB.T143dqy4bInOUpxLXNFCxi2GntZZDWC', 'ROLE_CONTRIBUTOR'),
 ('Viewer', 'viewer', 'viewer@domain.com', '$2a$10$AZkvnPuk4lJKg9vt/2cnB.T143dqy4bInOUpxLXNFCxi2GntZZDWC', 'ROLE_VIEWER');


insert into articles (title, author_id, is_public, content) values ('Mandatory tangible hub', 1, false, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into articles (title, author_id, is_public, content) values ('Customer-focused 24 hour pricing structure', 1, false, 'Donec quis orci eget orci vehicula condimentum.');
insert into articles (title, author_id, is_public, content) values ('Sharable scalable definition', 1, true, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.');
insert into articles (title, author_id, is_public, content) values ('Exclusive user-facing moratorium', 2, false, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into articles (title, author_id, is_public, content) values ('Switchable interactive conglomeration', 2, false, 'Donec vitae nisi.');
insert into articles (title, author_id, is_public, content) values ('Secured multimedia internet solution', 2, true, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into articles (title, author_id, is_public, content) values ('Integrated incremental success', 3, false, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into articles (title, author_id, is_public, content) values ('Fully-configurable transitional algorithm', 3, false, 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into articles (title, author_id, is_public, content) values ('Compatible demand-driven functionalities', 3, true, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into articles (title, author_id, is_public, content) values ('Realigned full-range contingency', 4, false, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into articles (title, author_id, is_public, content) values ('Triple-buffered background application', 4, false, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into articles (title, author_id, is_public, content) values ('Polarised intangible database', 4, true, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
